// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/rep/exchange/internal/app"
	"github.com/rep/exchange/internal/pkg/commom/config"
	"github.com/rep/exchange/internal/pkg/commom/logging"
	"github.com/rep/exchange/internal/pkg/currencyexchange"
	"github.com/rep/exchange/internal/pkg/currencyexchange/api"
	"github.com/rep/exchange/internal/pkg/webserver"
)

// Injectors from wire.go:

func initializeConfig(path string) (config.Configuration, error) {
	configuration, err := config.NewConfig(path)
	if err != nil {
		return config.Configuration{}, err
	}
	return configuration, nil
}

func initializeAppender(path string) (logging.FileAppender, error) {
	configuration, err := config.NewConfig(path)
	if err != nil {
		return logging.FileAppender{}, err
	}
	fileAppender := logging.NewFileAppender(configuration)
	return fileAppender, nil
}

func initializeApp(path string) (*app.ExchangeApp, error) {
	configuration, err := config.NewConfig(path)
	if err != nil {
		return nil, err
	}
	loggingLevels := config.NewLoggingLevels(configuration)
	loggerCurrency := logging.NewCurrency(loggingLevels)
	currencyManagerProxy := currencyexchange.NewCurrencyManagerProxy(loggerCurrency)
	loggerCalculator := logging.NewCalculator(loggingLevels)
	calculatorController := currencyexchange.NewCalculatorController(currencyManagerProxy, loggerCalculator)
	loggerAPIExchange := logging.NewLoggerAPIExchange(loggingLevels)
	controller := api.NewController(calculatorController, loggerAPIExchange)
	loggerWebServer := logging.NewWebServer(loggingLevels)
	paramWebServer := webserver.NewParamWebServer(controller, configuration, loggerWebServer)
	webServer := webserver.NewWebServer(paramWebServer)
	logger := logging.NewLogger(loggingLevels)
	exchangeApp := app.NewExchangeApp(webServer, logger)
	return exchangeApp, nil
}
