version: '3.3'
volumes:
  redisdb:
services:
  api:
    build: .
    env_file: '${PWD}/configs/config.env'
    ports: 
      - 3000:3000
    depends_on:
      - redisdb
  redisdb:
    image: redis:4.0.11-alpine3.8 
    command: redis-server --appendonly yes
    volumes:
      - redisdb:/data
    ports: 
      - 6379:6379
  redis-test:
    image: redis:4.0.11-alpine3.8 
    command: redis-server
    ports: 
      - 6380:6379
