// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package currencyexchange

import (
	"github.com/rep/exchange/internal/pkg/commom/config"
	"github.com/rep/exchange/internal/pkg/commom/logging"
	"github.com/rep/exchange/internal/pkg/infra/redis"
)

// Injectors from wire.go:

func initializeConfigTest() (config.Configuration, error) {
	string2 := newIntegrationConfigFile()
	configuration, err := config.NewConfig(string2)
	if err != nil {
		return config.Configuration{}, err
	}
	return configuration, nil
}

func initializeRedisTest(config2 config.Configuration) (redis.DBConnection, error) {
	redisDB := config.NewRedisDB(config2)
	loggingLevels := config.NewLoggingLevels(config2)
	loggerRedisDB := logging.NewRedisDB(loggingLevels)
	dbConnection, err := redis.NewDBConnection(redisDB, loggerRedisDB)
	if err != nil {
		return nil, err
	}
	return dbConnection, nil
}

func initializeCurrencyManagerDBTest(config2 config.Configuration) (*CurrencyManagerDB, error) {
	redisDB := config.NewRedisDB(config2)
	loggingLevels := config.NewLoggingLevels(config2)
	loggerRedisDB := logging.NewRedisDB(loggingLevels)
	dbConnection, err := redis.NewDBConnection(redisDB, loggerRedisDB)
	if err != nil {
		return nil, err
	}
	loggerCurrency := logging.NewCurrency(loggingLevels)
	currencyManagerDB := NewCurrencyManagerDB(dbConnection, loggerCurrency)
	return currencyManagerDB, nil
}
